name: Aquila Build Project

on:
  push:
    branches:
      - develop
      - main
      - release
      # - staging

jobs:
  tests_workflow:
    uses: ./.github/workflows/test-workflow.yml # Reutiliza o workflow de testes

  build_and_push_docker:
    runs-on: ubuntu-latest
    needs: test-workflow # Só executa se os testes passarem

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Build Docker image with cache
        run: |
          docker build --cache-from alexvoliveira/aquila:latest -t alexvoliveira/aquila:${{ github.sha }} .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image with commit SHA
        run: docker push alexvoliveira/aquila:${{ github.sha }}

      - name: Tag Docker image with context
        run: |
          tag_name="$(date +%Y%m%d)-${{ github.sha }}"
          docker tag alexvoliveira/aquila:${{ github.sha }} alexvoliveira/aquila:${tag_name}
          docker push alexvoliveira/aquila:${tag_name}
