name: Aquila SonarQube Analysis

on:
  workflow_run:
    workflows: ["Aquila Tests"]
    types:
      - completed

jobs:
  sonar:
    runs-on: ubuntu-latest
    needs: integration_tests
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.11.0"

      - name: Install dependencies
        run: npm install

      - name: Run SonarQube analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          npx sonarqube-scanner \
            -Dsonar.projectKey=Aquila-Project \
            -Dsonar.sources=src \
            -Dsonar.tests=__tests__ \
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov-report/lcov.info \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN
