name: Aquila Tests

on:
  workflow_call:
    inputs:
      some_input:
        required: false
        type: string

  pull_request:
    branches:
      - develop
      - main
      - release

jobs:
  lint_workflow:
    uses: ./.github/workflows/es-lint-workflow.yml

  unit_tests:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: lint_workflow
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.11.0"

      - name: Install dependencies
        run: npm install

      - name: Run Unit Tests
        run: npm run test:unit

  integration_tests:
    runs-on: ubuntu-latest
    needs: lint_workflow
    services:
      docker:
        image: docker:20.10.8-dind
        options: --privileged
        ports:
          - 2375:2375
        env:
          DOCKER_TLS_CERTDIR: ""

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.11.0"

      - name: Install dependencies
        run: npm install

      - name: Set up Docker
        run: docker info

      - name: Run Integration Tests
        run: npm run test:integration
